kind: Service
apiVersion: v1

metadata:
  name: robomarket-storefront-app
  labels:
    app: robomarket-storefront-app

spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: robomarket-storefront-app

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: robomarket-storefront-app
  labels:
    app: robomarket-storefront-app

spec:
  selector:
    matchLabels:
      app: robomarket-storefront-app
  template:
    metadata:
      name: robomarket-storefront-app
      labels:
        app: robomarket-storefront-app
    spec:
      containers:
        - name: robomarket-storefront-app
          image: 'registry.cozy.market/robokassa/robomarket-storefront-app:latest'

          imagePullPolicy: Always
          env:
            - name: "GET_HOSTS_FROM"
              value: "dns"

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
